/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aguapotable;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnull = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtnumcedula = new javax.swing.JTextField();
        btnnuevocobro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblnumfactura = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblcedid = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcantconsumida = new javax.swing.JTextField();
        btncalcular = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lblfechaactual = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblfechaultcob = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblconscobrar = new javax.swing.JLabel();
        btncobrar = new javax.swing.JButton();
        btncancelarfactura = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        menuhome = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        jMenuItem3.setText("jMenuItem3");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Drinwat");
        setBackground(new java.awt.Color(102, 102, 102));
        setIconImages(null);
        setName("home"); // NOI18N
        setState(3);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Drinwat");

        jLabel2.setText("Software de Facturación para Sistemas de Agua potable");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Copyleft © 2016 / Licencia GPL 3");

        txtnull.setOpaque(false);
        txtnull.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtnull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                .addComponent(txtnull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Facturación"));

        txtnumcedula.setForeground(new java.awt.Color(255, 51, 51));
        txtnumcedula.setText("Ingrese el número de cédula del cliente");
        txtnumcedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumcedulaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumcedulaFocusLost(evt);
            }
        });

        btnnuevocobro.setBackground(new java.awt.Color(51, 102, 255));
        btnnuevocobro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnnuevocobro.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevocobro.setText("Nuevo Cobro");
        btnnuevocobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevocobroActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Parroquia");
        jLabel3.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Belisario Quevedo");
        jLabel4.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Factura nº:");
        jLabel5.setEnabled(false);

        lblnumfactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnumfactura.setForeground(new java.awt.Color(255, 51, 51));
        lblnumfactura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblnumfactura.setText("0000000000");
        lblnumfactura.setEnabled(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Cliente:");
        jLabel7.setEnabled(false);

        lblnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnombre.setText("Nombe del Cliente");
        lblnombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblnombre.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Ced. Id:");
        jLabel9.setEnabled(false);

        lblcedid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcedid.setText("Cédula del Cliente");
        lblcedid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblcedid.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Detalles");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel12.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Cantidad consumida:");
        jLabel13.setEnabled(false);

        txtcantconsumida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcantconsumida.setText("0000000000");
        txtcantconsumida.setEnabled(false);
        txtcantconsumida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantconsumidaActionPerformed(evt);
            }
        });
        txtcantconsumida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcantconsumidaFocusGained(evt);
            }
        });

        btncalcular.setBackground(new java.awt.Color(51, 153, 255));
        btncalcular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncalcular.setForeground(new java.awt.Color(255, 255, 255));
        btncalcular.setText("Calcular");
        btncalcular.setEnabled(false);
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Fecha Actual:");
        jLabel14.setEnabled(false);

        lblfechaactual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfechaactual.setText("Junio 8 2016");
        lblfechaactual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblfechaactual.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Último Cobro:");
        jLabel16.setEnabled(false);

        lblfechaultcob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfechaultcob.setText("Mayo 8 2016");
        lblfechaultcob.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblfechaultcob.setEnabled(false);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCheckBox1.setText("Ene");
        jCheckBox1.setEnabled(false);

        jCheckBox2.setText("Feb");
        jCheckBox2.setEnabled(false);

        jCheckBox3.setText("Mar");
        jCheckBox3.setEnabled(false);

        jCheckBox4.setText("Abr");
        jCheckBox4.setEnabled(false);

        jCheckBox5.setText("May");
        jCheckBox5.setEnabled(false);

        jCheckBox6.setText("Jun");
        jCheckBox6.setEnabled(false);

        jCheckBox7.setText("Jul");
        jCheckBox7.setEnabled(false);

        jCheckBox8.setText("Ago");
        jCheckBox8.setEnabled(false);

        jCheckBox9.setText("Sep");
        jCheckBox9.setEnabled(false);

        jCheckBox10.setText("Oct");
        jCheckBox10.setEnabled(false);

        jCheckBox11.setText("Nov");
        jCheckBox11.setEnabled(false);

        jCheckBox12.setText("Dic");
        jCheckBox12.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jCheckBox8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox12)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Meses a cobrar en esta factura:");
        jLabel18.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Consumo a Cobrar:");
        jLabel19.setEnabled(false);

        lblconscobrar.setBackground(new java.awt.Color(255, 255, 255));
        lblconscobrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblconscobrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblconscobrar.setText("0000000000");
        lblconscobrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblconscobrar.setEnabled(false);
        lblconscobrar.setOpaque(true);

        btncobrar.setBackground(new java.awt.Color(51, 255, 51));
        btncobrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncobrar.setForeground(new java.awt.Color(255, 255, 255));
        btncobrar.setText("Cobrar");
        btncobrar.setEnabled(false);
        btncobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncobrarActionPerformed(evt);
            }
        });

        btncancelarfactura.setBackground(new java.awt.Color(255, 51, 51));
        btncancelarfactura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncancelarfactura.setForeground(new java.awt.Color(255, 255, 255));
        btncancelarfactura.setText("Cancelar");
        btncancelarfactura.setEnabled(false);
        btncancelarfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarfacturaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Powered by pakuapps.org");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Valor Total a Pagar por esta FACTURA:");
        jLabel22.setEnabled(false);

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("$");
        jLabel23.setEnabled(false);

        lbltotal.setBackground(new java.awt.Color(255, 255, 255));
        lbltotal.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbltotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltotal.setText("00.00");
        lbltotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbltotal.setEnabled(false);
        lbltotal.setOpaque(true);

        btnsave.setBackground(new java.awt.Color(51, 102, 255));
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Guardar");
        btnsave.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblcedid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcantconsumida, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btncalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblfechaactual, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblfechaultcob, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblconscobrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancelarfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblnombre)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantconsumida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblcedid)
                    .addComponent(btncalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblfechaactual)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lblfechaultcob))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblconscobrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltotal)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btncancelarfactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel21))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblnumfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(lblnumfactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtnumcedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnnuevocobro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnumcedula)
                    .addComponent(btnnuevocobro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu2.setText("Archivo");

        jMenuItem1.setText("Nuevo Cobro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Nuevo Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem6.setText("Editar Cliente");
        jMenu2.add(jMenuItem6);

        jMenuItem8.setText("Eliminar Cliente");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        menuhome.add(jMenu2);

        jMenu3.setText("Ver");

        jMenuItem4.setText("Reporte Diario");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem9.setText("Reporte Semanal");
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Reporte Mensual");
        jMenu3.add(jMenuItem10);

        menuhome.add(jMenu3);

        jMenu5.setText("Acerca de");

        jMenuItem5.setText("Desarrolladores");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem7.setText("El Equipo");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        menuhome.add(jMenu5);

        setJMenuBar(menuhome);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        //Begin-> Inicio de la Ventana DESARROLLADORES
            devs wdevs=new devs();
            wdevs.setVisible(true);
        //End-> Inicio de la Ventana DESARROLLADORES
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void txtcantconsumidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantconsumidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantconsumidaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Begin-> CIERRE de la Ventana LOGIN
        login wlogin=new login();
        wlogin.setVisible(false);
        //End-> CIERRE de la Ventana LOGIN
    }//GEN-LAST:event_formWindowActivated

    private void btnnuevocobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevocobroActionPerformed
        // TODO add your handling code here:
        String numcedula;
        numcedula = txtnumcedula.getText();
        if ("0919317768".equals(numcedula) || "0503793390".equals(numcedula)){
            numfact = numfact + 1;
            lblnumfactura.setText("00"+numfact);            
            jLabel3.setEnabled(true);
            jLabel4.setEnabled(true);
            jLabel5.setEnabled(true);
            jLabel7.setEnabled(true);
            jLabel13.setEnabled(true);
            jLabel9.setEnabled(true);
            jLabel12.setEnabled(true);
            jLabel14.setEnabled(true);
            jLabel16.setEnabled(true);
            jLabel18.setEnabled(true);
            jLabel19.setEnabled(true);
            jLabel21.setEnabled(true);
            jLabel22.setEnabled(true);
            jLabel23.setEnabled(true);
            lbltotal.setEnabled(true);
            jCheckBox1.setEnabled(true);
            jCheckBox2.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jCheckBox4.setEnabled(true);
            jCheckBox5.setEnabled(true);
            jCheckBox6.setEnabled(true);
            jCheckBox7.setEnabled(true);
            jCheckBox8.setEnabled(true);
            jCheckBox9.setEnabled(true);
            jCheckBox10.setEnabled(true);
            jCheckBox11.setEnabled(true);
            jCheckBox12.setEnabled(true);
            lblnumfactura.setEnabled(true);
            lblnombre.setEnabled(true);
            lblcedid.setEnabled(true);
            txtcantconsumida.setEnabled(true);
            lblfechaactual.setEnabled(true);
            lblfechaultcob.setEnabled(true);
            lblconscobrar.setEnabled(true);
            btncancelarfactura.setEnabled(true);        
            btncalcular.setEnabled(true);
            txtnumcedula.setEnabled(false);
            btnnuevocobro.setEnabled(false);
            txtnumcedula.setText("Ingrese el número de cédula del cliente");
            lblcedid.setText(numcedula);
        } else {
            if ("".equals(numcedula)){
                JOptionPane.showMessageDialog(null, "Por Favor,\nIngrese el número de cédula del cliente", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Lo sentimos, este cliente NO se ha\nencontrado en la Base de Datos", "Error", JOptionPane.ERROR_MESSAGE);
                txtnumcedula.grabFocus();
            }
        }
    }//GEN-LAST:event_btnnuevocobroActionPerformed

    private void btncancelarfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarfacturaActionPerformed
        //Begin-> Botón Cancelar
            //Begin-> Eliminar Contador de Factura Cancelada
                numfact = numfact - 1;
            //End-> Eliminar Contador de Factura Cancelada
            //Begin-> Reinicio de Objetos de Texto
                lblcedid.setText("Cédula del Cliente");
                txtcantconsumida.setText("0000000000");
                lblconscobrar.setText("0000000000");
                lbltotal.setText("00.00");
            //End-> Reinicio de Objetos de Texto
            //Begin->  Rehabilitación de Objetos de Búsqueda
                txtnumcedula.setEnabled(true);
                btnnuevocobro.setEnabled(true);
            //End->  Rehabilitación de Objetos de Búsqueda
            //Begin-> Reinicio de Objetos Comando de Facturación
                jLabel3.setEnabled(false);
                jLabel4.setEnabled(false);
                jLabel5.setEnabled(false);
                jLabel7.setEnabled(false);
                jLabel13.setEnabled(false);
                jLabel9.setEnabled(false);
                jLabel12.setEnabled(false);
                jLabel14.setEnabled(false);
                jLabel16.setEnabled(false);
                jLabel18.setEnabled(false);
                jLabel19.setEnabled(false);
                jLabel21.setEnabled(false);
                jLabel22.setEnabled(false);
                jLabel23.setEnabled(false);
                lbltotal.setEnabled(false);
                jCheckBox1.setEnabled(false);
                jCheckBox2.setEnabled(false);
                jCheckBox3.setEnabled(false);
                jCheckBox4.setEnabled(false);
                jCheckBox5.setEnabled(false);
                jCheckBox6.setEnabled(false);
                jCheckBox7.setEnabled(false);
                jCheckBox8.setEnabled(false);
                jCheckBox9.setEnabled(false);
                jCheckBox10.setEnabled(false);
                jCheckBox11.setEnabled(false);
                jCheckBox12.setEnabled(false);
                lblnumfactura.setEnabled(false);
                lblnombre.setEnabled(false);
                lblcedid.setEnabled(false);
                txtcantconsumida.setEnabled(false);
                lblfechaactual.setEnabled(false);
                lblfechaultcob.setEnabled(false);
                lblconscobrar.setEnabled(false);
                btncancelarfactura.setEnabled(false);
                btncobrar.setEnabled(false);         
                btncalcular.setEnabled(false);
                btnsave.setEnabled(false);
            //End-> Reinicio de Objetos Comando de Facturación
        //End Botón Cancelar
    }//GEN-LAST:event_btncancelarfacturaActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        //Begin-> Validación y Cálculo de Tarifa a Cobrar
            cantcons= Integer.parseInt(txtcantconsumida.getText());
            if (cantcons <= 0){
                JOptionPane.showMessageDialog(null, "Lo sentimos, NO puede ingresar valores menores o iguales a 0 (CERO)", "Error", JOptionPane.ERROR_MESSAGE);
                txtcantconsumida.grabFocus();
            } else {
                btnsave.setEnabled(true);
                btncobrar.setEnabled(true); 
                lblconscobrar.setText(txtcantconsumida.getText());
                total = (float) (Float.parseFloat(txtcantconsumida.getText())*(0.15));
                lbltotal.setText(" "+total+" ");               
            }
        //End-> Validación y Cálculo de Tarifa a Cobrar
    }//GEN-LAST:event_btncalcularActionPerformed

    private void txtnumcedulaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumcedulaFocusGained
        //Begin-> Cambios en la CAJA de ingreso de cédula para Búsqueda
            txtnumcedula.setForeground(Color.BLACK);
            txtnumcedula.setText(null);
        //End-> Cambios en la CAJA de ingreso de cédula para Búsqueda
    }//GEN-LAST:event_txtnumcedulaFocusGained

    private void txtnumcedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumcedulaFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtnumcedulaFocusLost

    private void txtcantconsumidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcantconsumidaFocusGained
        //Begin-> Iniciar con 0 a txtcantconsumida para evitar ERROR por CAJA Vacía
            txtcantconsumida.setText("0");
        //End-> Iniciar con 0 a txtcantconsumida para evitar ERROR por CAJA Vacía
    }//GEN-LAST:event_txtcantconsumidaFocusGained

    private void btncobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncobrarActionPerformed
        //Begin->Acciones del boton cobrar
            //Begin->Reinicio de Objetos
                JOptionPane.showMessageDialog(null, "El Cobro a sido efectuado exitósamente", "Drinwat", JOptionPane.INFORMATION_MESSAGE);
                //Begin->Reinicio de Objetos de Textos
                    txtcantconsumida.setText("0000000000");
                    lblconscobrar.setText("0000000000");
                    lbltotal.setText("00.00");
                    lblcedid.setText("Cédula del Cliente");
                //Begin->Reinicio de Objetos de Textos
                //Begin-> Rehabilitación de Objetos de Búsqueda
                    txtnumcedula.setEnabled(true);
                    btnnuevocobro.setEnabled(true);
                //End-> Rehabilitación de Objetos de Búsqueda
                //Begin-> Desabilitación de Objetos Comandos para COBRO
                    jLabel3.setEnabled(false);
                    jLabel4.setEnabled(false);
                    jLabel5.setEnabled(false);
                    jLabel7.setEnabled(false);
                    jLabel13.setEnabled(false);
                    jLabel9.setEnabled(false);
                    jLabel12.setEnabled(false);
                    jLabel14.setEnabled(false);
                    jLabel16.setEnabled(false);
                    jLabel18.setEnabled(false);
                    jLabel19.setEnabled(false);
                    jLabel21.setEnabled(false);
                    jLabel22.setEnabled(false);
                    jLabel23.setEnabled(false);
                    lbltotal.setEnabled(false);
                    jCheckBox1.setEnabled(false);
                    jCheckBox2.setEnabled(false);
                    jCheckBox3.setEnabled(false);
                    jCheckBox4.setEnabled(false);
                    jCheckBox5.setEnabled(false);
                    jCheckBox6.setEnabled(false);
                    jCheckBox7.setEnabled(false);
                    jCheckBox8.setEnabled(false);
                    jCheckBox9.setEnabled(false);
                    jCheckBox10.setEnabled(false);
                    jCheckBox11.setEnabled(false);
                    jCheckBox12.setEnabled(false);
                    lblnumfactura.setEnabled(false);
                    lblnombre.setEnabled(false);
                    lblcedid.setEnabled(false);
                    txtcantconsumida.setEnabled(false);
                    lblfechaactual.setEnabled(false);
                    lblfechaultcob.setEnabled(false);
                    lblconscobrar.setEnabled(false);
                    btncancelarfactura.setEnabled(false);
                    btncobrar.setEnabled(false);         
                    btncalcular.setEnabled(false);
                    btnsave.setEnabled(false);
                //End-> Desabilitación de Objetos Comandos para COBRO
            //End<-Reinicio de Objetos
        
        //Esto es para mandar a la tabla pero no puedo enviar de una win a otra (consultar)
        /*reportdia wreportdia=new reportdia();
        
        DefaultTableModel ing;
        ing = (DefaultTableModel) wreportdia.tabrepdias.getModel();
                Object[] in={vi};
                ing.addRow(in);
        */
        
        //End<-Acciones del botón cobrar
    }//GEN-LAST:event_btncobrarActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        //Begin-> INICIO de la Ventana EQUIPO
            team wteam=new team();
            wteam.setVisible(true);
        //End-> INICIO de la Ventana EQUIPO
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (txtnumcedula.isEnabled()){
            JOptionPane.showMessageDialog(null, "Ingrese el Número de Cédula del Cliente", "Nuevo Cobro", JOptionPane.INFORMATION_MESSAGE);
            txtnumcedula.grabFocus();            
        } else {
            JOptionPane.showMessageDialog(null, "Por Favor,\nTermine el actual cobro para efectuar uno nuevo!", "Nuevo Cobro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        //Begin-> INICIO de la Ventana REPORTE DIARIO
            reportdia wreportdia = new reportdia();
            wreportdia.setVisible(true);
        //End-> INICIO de la Ventana EQUIPO
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        newclient wnewclient=new newclient();
        wnewclient.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        delclient wdelclient = new delclient();
        wdelclient.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btncancelarfactura;
    private javax.swing.JButton btncobrar;
    private javax.swing.JButton btnnuevocobro;
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblcedid;
    private javax.swing.JLabel lblconscobrar;
    private javax.swing.JLabel lblfechaactual;
    private javax.swing.JLabel lblfechaultcob;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnumfactura;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JMenuBar menuhome;
    private javax.swing.JTextField txtcantconsumida;
    private javax.swing.JTextField txtnull;
    private javax.swing.JTextField txtnumcedula;
    // End of variables declaration//GEN-END:variables
    //Begin-> Declaración e Inicialización de Variables GLOBALES
        float total=0, vi=0;
        int cantcons=0;
        int numfact=0;
    //End-> Declaración e Inicialización de Variables GLOBALES
}
